parameters:
  - name: JarFileDirectory
    type: string

steps:
  - task: AzureKeyVault@2
    displayName: "Get GnuPG signing keys"
    inputs:
      #The value below is the name of an ADO service connection.
      azureSubscription: "AIInfraBuildOnnxRuntimeOSS"
      KeyVaultName: "ort-release"
      SecretsFilter: "java-pgp-pwd,java-pgp-key"
      RunAsPreJob: false

  - task: UsePythonVersion@0
    displayName: "Use Python 3.12"
    inputs:
      versionSpec: "3.12"

  - task: PythonScript@0
    displayName: "Sign files: GnuPG, sha1, and md5"
    inputs:
      scriptPath: "$(Build.SourcesDirectory)/tools/ci_build/github/windows/sign_java_artifacts.py"
      arguments: "${{ parameters.JarFileDirectory }}"
      workingDirectory: "$(Build.SourcesDirectory)"