# This template packages the Java artifacts for either CPU or GPU.
# It calls the PowerShell script with the correct package type and ensures
# that the correct final JAR file is signed and published.

parameters:
  - name: package_type
    type: string
    default: 'cpu'
    values:
      - 'cpu'
      - 'gpu'

variables:
  # Set the package name variable based on the template parameter.
  # This will be used to construct the correct JAR filename for signing.
  - name: packageName
    ${{ if eq(parameters.package_type, 'gpu') }}:
      value: 'onnxruntime_gpu'
    ${{ if eq(parameters.package_type, 'cpu') }}:
      value: 'onnxruntime'

steps:
- checkout: self
  submodules: false

- template: set-version-number-variables-step.yml

- task: PowerShell@2
  displayName: 'Package Java Artifacts (${{ parameters.package_type }})'
  inputs:
    targetType: filePath
    filePath: $(Build.SourcesDirectory)\tools\ci_build\github\windows\jar_packaging.ps1
    arguments: '-PackageType ${{ parameters.package_type }}'
    failOnStderr: true
    showWarnings: true
    workingDirectory: '$(Build.BinariesDirectory)\java-artifact'

- template: jar-esrp-dll.yml
  parameters:
    JarFileDirectory: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'
    # Use the variable to ensure the correct JAR file is signed
    JarFileName: '$(packageName)-$(OnnxRuntimeVersion).jar'

- template: jar-maven-signing-win.yml
  parameters:
    JarFileDirectory: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'

- task: CopyFiles@2
  displayName: 'Copy Java Files to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'