# This template packages the Java artifacts for either CPU or GPU.
# It calls the PowerShell script with the correct package type and ensures
# that the correct final JAR file is signed and published.

parameters:
  - name: package_type
    type: string
    default: 'cpu'
    values:
      - 'cpu'
      - 'gpu'

steps:
- checkout: self
  submodules: false

- template: set-version-number-variables-step.yml


- task: PythonScript@0
  displayName: 'Package Java Artifacts'
  inputs:
    scriptPath: $(Build.SourcesDirectory)\tools\ci_build\jar_packaging.ps1
    arguments: '--package_type ${{ parameters.package_type }}'
    workingDirectory: '$(Build.BinariesDirectory)\java-artifact'

- template: jar-esrp-dll.yml
  parameters:
    JarFileDirectory: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'
    ${{ if eq(parameters.package_type, 'gpu') }}:
      JarFileName: '$(onnxruntime_gpu)-$(OnnxRuntimeVersion).jar'
    ${{ if eq(parameters.package_type, 'cpu') }}:
      JarFileName: '$(onnxruntime)-$(OnnxRuntimeVersion).jar'

- template: jar-maven-signing-win.yml
  parameters:
    JarFileDirectory: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'

- task: CopyFiles@2
  displayName: 'Copy Java Files to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'