parameters:
  - name: msbuildPlatform
    type: string
  - name: java_artifact_id
    type: string
  - name: buildOnly
    type: boolean
    default: false

steps:
- task: PowerShell@2
  displayName: 'Build and Package Java Artifacts'
  inputs:
    targetType: 'inline'
    script: |
      # Define arguments for the Python script
      $scriptArgs = @(
        "--sources-dir", "$(Build.SourcesDirectory)",
        "--binaries-dir", "$(Build.BinariesDirectory)",
        "--platform", "${{ parameters.msbuildPlatform }}",
        "--java-artifact-id", "${{ parameters.java_artifact_id }}",
        "--base-version", "$(OnnxRuntimeVersion)",
        "--version-suffix", "$(ReleaseVersionSuffix)",
        "--commit-hash", "$(OnnxRuntimeGitCommitHash)"
      )

      # Conditionally add the --build-only flag if the parameter is true
      if ('${{ parameters.buildOnly }}' -eq 'True') {
        $scriptArgs += "--build-only"
      }

      # Define the path to the python script within your repository
      $scriptPath = "$(Build.SourcesDirectory)/tools/ci_build/manage_java_artifacts.py"

      # Execute the Python script, passing all arguments
      Write-Host "Executing Python script: $scriptPath with arguments: $($scriptArgs -join ' ')"
      python $scriptPath $scriptArgs