steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'OnnxrunTimeCodeSign_20240611'
    azurePowerShellVersion: 'LatestVersion'
    scriptType: 'InlineScript'
    inline: |
       $authScope = "https://mspmecloud.onmicrosoft.com/RebuildManager.Web/.default"
       $env:TRT_UPLOAD_AUTH_TOKEN = (Get-AzAccessToken -ResourceUri $authScope).Token
       &C:\local\Terrapin\TerrapinRetrievalTool.exe -b https://vcpkg.storage.devpackages.microsoft.io/artifacts/ -a true -u Environment -p https://dlcdn.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.zip -s 03e2d65d4483a3396980629f260e25cac0d8b6f7f2791e4dc20bc83f9514db8d0f05b0479e699a5f34679250c49c8e52e961262ded468a20de0be254d8207076 -d $(Agent.TempDirectory)\maven.zip
       if ($LASTEXITCODE -ne 0) {
        throw "Error downloading maven. Exit code: $LASTEXITCODE"
       }
       $arguments = "x", "$(Agent.TempDirectory)\maven.zip", "-y", "-o$(Agent.TempDirectory)"
       Write-Output "Executing: 7z.exe $arguments"
       & 7z.exe $arguments
       if ($LASTEXITCODE -ne 0) {
           throw "Error extracting '$($_.FullName)'. Exit code: $LASTEXITCODE"
       }
       Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\apache-maven-3.9.11"

- script: |
    mvn --version