parameters:
- name: actionVersion
  type: string
  default: 'v0.0.7' # Default version if not specified by the calling pipeline

steps:
- task: DownloadGitHubRelease@0
  displayName: 'Download Action Release ${{ parameters.actionVersion }}'
  inputs:
    connection: 'microsoft'
    userRepository: 'microsoft/onnxruntime-github-actions'
    defaultVersionType: specificTag
    version: '${{ parameters.actionVersion }}'
    itemPattern: '**/*.zip'
    downloadPath: '$(System.ArtifactsDirectory)/action-download'

- task: ExtractFiles@1
  displayName: 'Extract Action Files'
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/action-download/**/*.zip'
    destinationFolder: '$(System.ArtifactsDirectory)/action-unzipped'
    cleanDestinationFolder: true

- script: ls '$(System.ArtifactsDirectory)/action-unzipped'

- task: PythonScript@0
  displayName: 'Run GitHub Action via Python Wrapper'
  inputs:
    scriptPath: 'tools/ci_build/run_gh_action.py'
    arguments: '${{ parameters.actionVersion }}'

- bash: |
    echo "Verifying CMake installation..."
    cmake --version
    echo "Verifying vcpkg installation..."
    $VCPKG_INSTALLATION_ROOT/vcpkg version
  displayName: 'Verify Tools'