parameters:
- name: actionVersion
  type: string
  default: 'v0.0.7'

steps:
- script: python3 -m pip install requests

- task: PythonScript@0
  displayName: 'Run GitHub Action via Python Wrapper'
  inputs:
    scriptPath: 'tools/ci_build/run_gh_action.py'
    arguments: '${{ parameters.actionVersion }}'

- bash: |
    echo "Verifying CMake installation..."
    cmake --version
    echo "Verifying vcpkg installation..."
    $VCPKG_INSTALLATION_ROOT/vcpkg version
  displayName: 'Verify Tools'