steps:
- task: PythonScript@0
  displayName: 'Download and Run setup-build-tools Action'
  inputs:
    scriptSource: 'inline'
    script: |
      import os
      import subprocess
      import requests
      import zipfile
      import shutil
      import glob

      # --- 1. Define Action Inputs ---
      # These will be set as environment variables for the node script.
      # NOTE: Replace the placeholder hashes with actual, valid SHA512 hashes.
      action_inputs = {
          'INPUT_CMAKE-VERSION': '3.31.8',
          'INPUT_CMAKE-HASH': '99cc9c63ae49f21253efb5921de2ba84ce136018abf08632c92c060ba91d552e0f6acc214e9ba8123dee0cf6d1cf089ca389e321879fd9d719a60d975bcffcc8',
          'INPUT_VCPKG-VERSION': '2025.06.13',
          'INPUT_VCPKG-HASH': '735923258c5187966698f98ce0f1393b8adc6f84d44fd8829dda7db52828639331764ecf41f50c8e881e497b569f463dbd02dcb027ee9d9ede0711102de256cc',
          'INPUT_ADD-CMAKE-TO-PATH': 'true',
          'INPUT_DISABLE-TERRAPIN': 'true'
      }

      # --- 2. Download and Extract the Action Source ---
      action_version = "v0.0.7" # Specify the release tag to use
      zip_url = f"https://github.com/microsoft/onnxruntime-github-actions/archive/refs/tags/{action_version}.zip"
      zip_path = "onnxruntime-actions.zip"
      extract_dir = "unzipped_action_src"
      
      print(f"Downloading action source from: {zip_url}")
      response = requests.get(zip_url, stream=True)
      response.raise_for_status()
      with open(zip_path, 'wb') as f:
          shutil.copyfileobj(response.raw, f)
      
      print(f"Extracting {zip_path} to {extract_dir}")
      if os.path.exists(extract_dir):
          shutil.rmtree(extract_dir)
      with zipfile.ZipFile(zip_path, 'r') as zip_ref:
          zip_ref.extractall(extract_dir)

      # --- 3. Run the Action Script (No Build Step Needed) ---
      # Find the actual extracted folder name (it's usually repo-name-tag)
      extracted_folders = glob.glob(os.path.join(extract_dir, 'onnxruntime-github-actions-*'))
      if not extracted_folders:
          raise Exception("Could not find extracted action source directory.")
      action_base_path = extracted_folders[0]
      print(f"Found action source at: {action_base_path}")
      
      action_script_path = os.path.join(action_base_path, 'actions', 'setup-build-tools', 'dist', 'index.js')

      if not os.path.exists(action_script_path):
          raise FileNotFoundError(f"Action script not found at the expected path: {action_script_path}")
          
      # Set environment variables for the action
      env = os.environ.copy()
      env.update(action_inputs)

      print(f"Running action script: {action_script_path}")
      with open('action_output.log', 'w') as log_file:
          process = subprocess.run(
              ['node', action_script_path],
              env=env,
              stdout=log_file,
              stderr=subprocess.STDOUT,
              text=True
          )
      
      print("Action script finished.")
      if process.returncode != 0:
          print(f"##vso[task.logissue type=error]Action script failed with exit code {process.returncode}.")
          with open('action_output.log', 'r') as log_file:
              print(log_file.read())
          exit(1)

- bash: |
    echo "Searching for paths added by the action..."
    # Search the log file for the specific pattern indicating a path addition.
    added_paths=$(grep -oP '(?<=Adding ).*(?= to PATH.)' action_output.log)

    if [ -z "$added_paths" ]; then
      echo "No new paths were found in the action's output."
    else
      echo "Found paths to add to the environment:"
      echo "$added_paths"
      
      # Loop through each found path and prepend it to the ADO job's PATH
      while IFS= read -r path; do
        if [ -n "$path" ]; then
          echo "Prepending to PATH: $path"
          # Use the special Azure Pipelines logging command to prepend a directory to the PATH
          echo "##vso[task.prependpath]$path"
        fi
      done <<< "$added_paths"
    fi
  displayName: 'Update ADO Job PATH from Action Output'

- bash: |
    echo "Verifying CMake installation by checking its version..."
    cmake --version
    echo "Verifying vcpkg installation by checking its version..."
    # The action sets VCPKG_INSTALLATION_ROOT as an environment variable for the script,
    # and ADO should pick it up for subsequent steps if it was exported correctly.
    $VCPKG_INSTALLATION_ROOT/vcpkg version
  displayName: 'Verify Tools'