#!/usr/bin/env python3
"""
publish_primitives.py – Stage 3: Publish / Sync Primitives

Reads refined + scored primitives and:
  1. Syncs them into metop/hyping/<slug>/ on disk.
  2. Generates / refreshes the global index (metop/hyping/index.json).
  3. Writes a human-readable run manifest to metop/hyping/run_manifest.json.
  4. Generates per-ingredient Markdown reports into
     metop/hyping/<slug>/reports/<slug>_report.md

Usage:
  python publish_primitives.py [--output-root <path>] [--dry-run]
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from hypergredient_framework import HYPERGREDIENT_DATABASE  # noqa: E402
from generate_primitives import slugify  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SCHEMA_VERSION = "1.0.0"
PIPELINE_STAGE = "published"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_json(path: Path) -> Optional[Dict[str, Any]]:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def _generate_report(slug: str, scored: Dict[str, Any], refined: Dict[str, Any]) -> str:
    """Return a Markdown report string for an ingredient."""
    identity = scored.get("identity", {})
    classification = scored.get("classification", {})
    safety = scored.get("safety_stability_cost", {})
    metrics = scored.get("optimization_metrics", {})
    relationships = scored.get("relationships", {})
    benchmark = scored.get("benchmark", {})
    ai_insights = refined.get("ai_insights", {})

    lines = [
        f"# {identity.get('name', slug)} – Hypergredient Primitive Report",
        "",
        f"> **Slug:** `{slug}`  ",
        f"> **Class:** `{classification.get('hypergredient_class', '?')}` – "
        f"{classification.get('class_description', '')}  ",
        f"> **INCI:** {identity.get('inci_name', '?')}",
        "",
        "## Classification",
        "",
        f"- **Primary function:** {classification.get('primary_function', '?')}",
        "- **Secondary functions:** "
        + ", ".join(classification.get("secondary_functions", []) or ["—"]),
        "",
        "## Optimization Metrics",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Efficacy score | {metrics.get('efficacy_score', '?')}/10 |",
        f"| Bioavailability | {metrics.get('bioavailability', '?')} |",
        f"| Synergy score | {metrics.get('synergy_score', '?')}/10 |",
        f"| Confidence score | {metrics.get('confidence_score', '?')} |",
        "",
        "## Safety, Stability & Cost",
        "",
        f"| Property | Value |",
        f"|---|---|",
        f"| Safety score | {safety.get('safety_score', '?')}/10 |",
        f"| Clinical evidence | {safety.get('clinical_evidence', '?')} |",
        f"| pH range | {safety.get('pH_min', '?')} – {safety.get('pH_max', '?')} |",
        f"| Stability | {json.dumps(safety.get('stability_conditions', {}))} |",
        f"| Cost (ZAR/g) | {safety.get('cost_per_gram_zar', '?')} |",
        "",
        "## Relationships",
        "",
        "**Synergies:** " + (", ".join(relationships.get("synergies") or []) or "—"),
        "",
        "**Incompatibilities:** "
        + (", ".join(relationships.get("incompatibilities") or []) or "—"),
        "",
        "## Benchmark",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Multi-objective score | {benchmark.get('multi_objective_score', '?')} |",
        f"| Stability label | {benchmark.get('stability_label', '?')} |",
        f"| pH range width | {benchmark.get('ph_range_width', '?')} |",
        f"| Cost tier | {benchmark.get('cost_tier', '?')} |",
        "",
        "## AI Insights",
        "",
        f"- **Model version:** {ai_insights.get('model_version', '?')}",
        "- **Ranked concerns:** "
        + ", ".join(ai_insights.get("ranked_concerns") or []) or "—",
        "",
        "---",
        f"*Generated by publish_primitives.py at stage `{PIPELINE_STAGE}`*",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Core publish logic
# ---------------------------------------------------------------------------

def publish(output_root: Path, dry_run: bool) -> Dict[str, Any]:
    run_ts = time.time()
    hyping_root = output_root / "hyping"

    if not hyping_root.is_dir():
        print(
            f"❌ hyping root not found: {hyping_root}\n"
            "   Run generate_primitives.py and refine_primitives.py first.",
            file=sys.stderr,
        )
        return {}

    index_entries: List[Dict[str, Any]] = []
    stats_by_class: Dict[str, int] = {}
    stats_by_category: Dict[str, int] = {}
    count = 0

    # Iterate over existing ingredient directories
    for ingredient_dir in sorted(hyping_root.iterdir()):
        if not ingredient_dir.is_dir():
            continue
        slug = ingredient_dir.name

        scored_path = ingredient_dir / "scored" / f"{slug}_scored.json"
        refined_path = ingredient_dir / "refined" / f"{slug}.json"

        scored = _load_json(scored_path)
        refined = _load_json(refined_path)

        if scored is None:
            print(f"  ⚠  Skipping {slug}: scored primitive not found at {scored_path}")
            continue

        if refined is None:
            print(f"  ⚠  Skipping {slug}: refined primitive not found at {refined_path}")
            continue

        # Generate and write the Markdown report
        report_md = _generate_report(slug, scored, refined)
        report_path = ingredient_dir / "reports" / f"{slug}_report.md"

        if not dry_run:
            report_path.parent.mkdir(parents=True, exist_ok=True)
            report_path.write_text(report_md)

        # Collect index metadata
        hg_class = scored.get("classification", {}).get("hypergredient_class", "?")
        primary_fn = scored.get("classification", {}).get("primary_function", "?")
        confidence = scored.get("optimization_metrics", {}).get("confidence_score")
        synergy = scored.get("optimization_metrics", {}).get("synergy_score")

        index_entry = {
            "slug": slug,
            "name": scored.get("identity", {}).get("name", slug),
            "inci_name": scored.get("identity", {}).get("inci_name", ""),
            "hypergredient_class": hg_class,
            "class_description": HYPERGREDIENT_DATABASE.get(hg_class, ""),
            "primary_function": primary_fn,
            "confidence_score": confidence,
            "synergy_score": synergy,
            "paths": {
                "raw": str((ingredient_dir / "raw" / f"{slug}.json").relative_to(output_root)),
                "refined": str(refined_path.relative_to(output_root)),
                "scored": str(scored_path.relative_to(output_root)),
                "report": str(report_path.relative_to(output_root)),
            },
        }
        index_entries.append(index_entry)

        stats_by_class[hg_class] = stats_by_class.get(hg_class, 0) + 1
        stats_by_category[primary_fn] = stats_by_category.get(primary_fn, 0) + 1

        status = "[DRY-RUN]" if dry_run else "✓"
        print(f"  {status} {slug}  [{hg_class}]  confidence={confidence}")
        count += 1

    # Global index
    index = {
        "schema_version": SCHEMA_VERSION,
        "pipeline_stage": PIPELINE_STAGE,
        "published_at": run_ts,
        "publisher": "publish_primitives.py",
        "total_ingredients": count,
        "hypergredient_classes": sorted(HYPERGREDIENT_DATABASE.keys()),
        "stats_by_class": stats_by_class,
        "stats_by_primary_function": stats_by_category,
        "entries": sorted(index_entries, key=lambda e: e["slug"]),
    }
    index_file = hyping_root / "index.json"

    # Run manifest
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "run_at": run_ts,
        "stage": PIPELINE_STAGE,
        "total_published": count,
        "stats_by_class": stats_by_class,
        "stats_by_primary_function": stats_by_category,
    }
    manifest_file = hyping_root / "run_manifest.json"

    if not dry_run:
        index_file.write_text(json.dumps(index, indent=2, sort_keys=True))
        manifest_file.write_text(json.dumps(manifest, indent=2, sort_keys=True))
        print(f"\n📋 Index written     → {index_file}")
        print(f"📋 Manifest written  → {manifest_file}")
    else:
        print(f"\n[DRY-RUN] Would write index    → {index_file}")
        print(f"[DRY-RUN] Would write manifest → {manifest_file}")

    return manifest


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Publish refined hypergredient primitives and refresh the global index."
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "metop",
        help="Root directory for primitive output tree (default: <repo>/metop)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written without creating any files.",
    )
    args = parser.parse_args()

    print("📦 Hypergredient Primitive Publisher – Stage 3: publish")
    print(f"   Output root : {args.output_root}")
    print(f"   Dry-run     : {args.dry_run}\n")

    manifest = publish(args.output_root, args.dry_run)
    total = manifest.get("total_published", 0)

    print(f"\n✅ Done – {total} primitives {'would be ' if args.dry_run else ''}published.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
